// alon - Thu Jan 13 08:50:54 2022
// Restaurant Customers (https://cses.fi/problemset/task/1619)
// Generated by cptk
 
#include <bits/stdc++.h>
using namespace std;
 
#define int long long
#define all(x) (x).begin(), (x).end()
 
typedef vector<int> vi;
typedef pair<int, bool> ib;
 
void solve();
signed main() {
    cin.tie(NULL)->sync_with_stdio(false);
    cout << fixed;
    cout.precision(10);
    int t = 1;
    // cin >> t;
    while (t--) solve();
}
 
void solve() {
    int n, t;
    cin >> n;
 
    vector<ib> a(2 * n);
 
    for (int i = 0; i < n; i++) {
        cin >> t;
        a[2 * i] = {t, true};
        cin >> t;
        a[2 * i + 1] = {t, false};
    }
 
    sort(all(a));
 
    int ma = 0, cur = 0;
    for (ib& b : a) {
        cur += (b.second ? 1 : -1);
        ma = max(ma, cur);
    }
 
    cout << ma << endl;
}
