export PROBLEM = 1671-Shortest_Routes_I-training-23/03/2024 08:04
export CPPFLAGS = -DONLINE_JUDGE -std=c++17 -O2
export OUTPUT = > /dev/null 2>&1
export TEST = ../test/entry06.txt ../test/entry07.txt ../test/entry08.txt ../test/entry09.txt ../test/entry10.txt ../test/entry11.txt ../test/entry18.txt ../test/entry19.txt ../test/entry20.txt ../test/entry21.txt ../test/entry22.txt 
all:
	+$(MAKE) -C training
clean:
	rm rand/*.exe training/*.exe control/*.exe
