export PROBLEM = 1642-Sum_of_Four_Values-training-23-04-2024-14-28-think
export CPPFLAGS = -DONLINE_JUDGE -std=c++17 -O2
export OUTPUT = > /dev/null 2>&1
export TEST = ../test/entry09.txt ../test/entry10.txt ../test/entry11.txt ../test/entry12.txt ../test/entry13.txt ../test/entry14.txt ../test/entry17.txt ../test/entry18.txt ../test/entry19.txt ../test/entry23.txt ../test/entry26.txt 
all:
	+$(MAKE) -C training
clean:
	rm rand/*.exe training/*.exe control/*.exe
