export PROBLEM = 1668-Building_Teams-training-23-04-2024-14-28-think
export CPPFLAGS = -DONLINE_JUDGE -std=c++17 -O2
export OUTPUT = > /dev/null 2>&1
export TEST = ../test/entry06.txt ../test/entry07.txt ../test/entry08.txt ../test/entry09.txt ../test/entry10.txt 
all:
	+$(MAKE) -C training
clean:
	rm rand/*.exe training/*.exe control/*.exe
