export PROBLEM = 1619-Restaurant_Customers-training-23-04-2024-14-28-think
export CPPFLAGS = -DONLINE_JUDGE -std=c++17 -O2
export OUTPUT = > /dev/null 2>&1
export TEST = ../test/entry04.txt ../test/entry05.txt ../test/entry06.txt ../test/entry08.txt ../test/entry10.txt 
all:
	+$(MAKE) -C training
clean:
	rm rand/*.exe training/*.exe control/*.exe
