export PROBLEM = 2166-Prefix_Sum_Queries-training-23-03-2024-08-13
export CPPFLAGS = -DONLINE_JUDGE -std=c++17 -O2
export OUTPUT = > /dev/null 2>&1
export TEST = ../test/entry02.txt ../test/entry06.txt 
all:
	+$(MAKE) -C training
clean:
	rm rand/*.exe training/*.exe control/*.exe
