export PROBLEM = baseline-elite
export CPPFLAGS = -DONLINE_JUDGE -std=c++17 -O2
export OUTPUT = > /dev/null 2>&1
export TEST = ../test/entry01.txt 
all:
	+$(MAKE) -C rand
clean:
	rm rand/*.exe training/*.exe control/*.exe
